#!/bin/bash
 
export NAME="dss"                                  # Name of the application
export DJANGODIR=$(pwd)/$NAME             # Django project directory
export ENVDIR=$(pwd)/env		 # Virtual enviroment directory
export SOCKFILE=$(pwd)/run/gunicorn.sock  # we will communicte using this unix socket
export NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
export DJANGO_SETTINGS_MODULE=dss.gunicorn_settings             # which settings file should Django use
export DJANGO_WSGI_MODULE=dss.wsgi                     # WSGI module name

echo "Starting $NAME as `ewatec`"
echo $(pwd)

# Activate the virtual environment
source $ENVDIR/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$ENVDIR
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $ENVDIR/bin/gunicorn ${DJANGO_WSGI_MODULE}:application\
  --bind=unix:$SOCKFILE\ 
  --timeout 3600\
  --workers $NUM_WORKERS\
  --log-level=debug\
  --log-file=-
